name: Deploy production

on:
  push:
    tags:
      - 'v*'

jobs:

  deploy-package:
    name: Deploy package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: darwinia-network/devops
          path: .github/actions

      - uses: ./.github/actions/smart-vercel
        name: Deploy app
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          prod_mode: true
          project_name: "crosschain-ui"
          script_run: false
          dist_path: .
          enable_notify_slack: true
          slack_channel: darwinia-apps
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

